version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    working_dir: /app
    env_file:
      - .env
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/DB

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: ["go", "run", "main.go"]

volumes:
  db_data:
